import pygame as pg
import precode2 as pc
import main

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 1600
SCREENSIZE = [SCREEN_WIDTH, SCREEN_HEIGHT]
GRAVITY = 2
FUEL = 100

PINK = (241, 84, 185)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

P1_KEY_ENGINE = pg.K_UP
P1_KEY_LEFT = pg.K_LEFT
P1_KEY_RIGHT = pg.K_RIGHT
P1_KEY_SHOOT = pg.K_DOWN

P2_KEY_ENGINE = pg.K_w
P2_KEY_LEFT = pg.K_a
P2_KEY_RIGHT = pg.K_d
P2_KEY_SHOOT = pg.K_SPACE

TEXT_SIZE = 50
OBSTACLES_SIZE = 1

FUELTANK_SIZE = 100

SCORE_COLLISION = 10
SCORE_HIT = 10
SCORE_SHOT = 10

FUEL_LOOSE = 0.7
FUEL_ADD = 50

BULLET_SIZE = 3

OBS_SCALE = 1
